spring.application.name=bugpilot-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/bugpilot
spring.datasource.username=postgres
spring.datasource.password=Bug@144
spring.jpa.hibernate.ddl-auto=update